### ISSUE TITLE
throw new Error('invalid argument: `family` must be 4 or 6')

### ISSUE THREAD

**Issue by mozillazg** [spmjs/spm2#114]
Ubuntu 13.10

```
$ spm -V
2.2.4

$ spm install alice/one

        install: alice/one@stable
          fetch: alice/one@stable

dns.js:113
      throw new Error('invalid argument: `family` must be 4 or 6');
            ^
Error: invalid argument: `family` must be 4 or 6
    at Object.exports.lookup (dns.js:113:13)
    at Socket.connect (net.js:871:20)
    at Agent.exports.connect.exports.createConnection (net.js:85:35)
    at Agent.createSocket (_http_agent.js:196:16)
    at Agent.addRequest (_http_agent.js:168:23)
    at new ClientRequest (_http_client.js:122:16)
    at Agent.request (_http_agent.js:301:10)
    at Object.exports.request (http.js:52:22)
    at Request.start (/home/xxx/local/lib/node_modules/spm/node_modules/request/index.js:604:30)
    at Request.end (/home/xxx/local/lib/node_modules/spm/node_modules/request/index.js:1211:28)
```

`spm install jquery/jquery` 也是相同的问题

**Comment by afc163** [comment]
感觉像网络问题。

```
curl https://spmjs.org
```

**Comment by mozillazg** [comment]
网络没问题：

```
$ curl https://spmjs.org -I
HTTP/1.1 200 OK
Server: nginx/1.2.8
Date: Wed, 25 Dec 2013 03:16:29 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 8145
Connection: keep-alive
Set-Cookie: yuan="LKoPQoicrvT0X/710mKkoJ2Y8po=?identity.auth_type=UycnCi4=&identity.name=Uyd5dWFuJwpwMQou"; Path=/; HttpOnly
```

**Comment by afc163** [comment]
http://nodejs.org/api/dns.html#dns_dns_lookup_domain_family_callback

试试看

```
Nslookup spmjs.org
```

**Comment by afc163** [comment]
https://github.com/joyent/node/blob/master/lib/dns.js#L113

**Comment by mozillazg** [comment]
```
$ nslookup spmjs.org
Server:     127.0.1.1
Address:    127.0.1.1#53

Non-authoritative answer:
Name:   spmjs.org
Address: 173.230.152.184
```

**Comment by afc163** [comment]
node 版本是？

**Comment by mozillazg** [comment]
```
$ node --version
v0.11.10-pre
···
```

**Comment by mozillazg** [comment]
我是不是应该重装一下 node ?

**Comment by afc163** [comment]
好新的版本，其实我不知道。

你试试 0.10.x 的稳定版本看看？

**Comment by mozillazg** [comment]
嗯，版本是比较新。
当时是看了你们在 #83 上的讨论，通过编译官方仓库的源码安装的版本。
重装了 v0.10.24 的稳定版后问题解决了。
