### ISSUE TITLE
spm2 安装出错，连接超时

### ISSUE THREAD

**Issue by huangwenping** [spmjs/spm2#5]
node -v v0.10.0
npm -v  1.2.14
无论是 通过 npm 还是 下载 git 源码 安装 都不行，应该是某个网络连接有问题，但又找不到具体是哪个，在这里一段卡了很久： 

```
grunt@0.4.0 (which@1.0.5, dateformat@1.0.2-1.2.3, colors@0.6.0-1, hooker@0.2.3,    eventemitter2@0.4.11, minimatch@0.2.11, coffee-script@1.3.3, iconv-lite@0.2.7, underscore.string@2.2.0rc, glob@3.1.21, rimraf@2.0.3, nopt@1.0.10, findup-sync@0.1.2, js-yaml@1.0.3)
```

下面是log 

```
  1 11775 error Error: read ETIMEDOUT
  2 11775 error     at errnoException (net.js:863:11)
  3 11775 error     at TCP.onread (net.js:524:19)
  4 11776 error If you need help, you may report this log at:
  5 11776 error     <http://github.com/isaacs/npm/issues>
  6 11776 error or email it to:
  7 11776 error     <npm-@googlegroups.com>
  8 11777 error System Darwin 12.3.0
  9 11778 error command "node" "/usr/local/bin/npm" "install" "." "-g"
 10 11779 error cwd /Users/hwp/Frontend/nodejs/spm2
 11 11780 error node -v v0.10.0
 12 11781 error npm -v 1.2.14
 13 11782 error syscall read
 14 11783 error code ETIMEDOUT
 15 11784 error errno ETIMEDOUT
 16 11785 verbose exit [ 1, true ]
~                                         
```

**Comment by lepture** [comment]
@huangwenping 这是 npm 的问题，你可以试着安装一下 grunt

```
$ npm install grunt
```

**Comment by lepture** [comment]
@huangwenping 另外，目前还处于 beta，接口可能会有变化，请注意关注文档进展。

**Comment by huangwenping** [comment]
好的，谢了。希望尽早推出稳定版

**Comment by wood8** [comment]
我也有类似问题,我的是连接重置了,但是我装grunt也是这样.

**Comment by xsbear** [comment]
应该主要是网络问题，导致有些npm包不能正常下载，我在公司网络不行，家里还行。给npm 配个http_proxy就可以了
