### ISSUE TITLE
spm组件名字问题

### ISSUE THREAD

**Issue by willkan** [spmjs/spm2#86]
我publish了一个组件:willkan/backbone.localStorage,
但当我install时，spm install willkan/backbone.localStorage，会报错，应该时组件名字中的`.`导致的问题，请问该怎么安装这类组件

```
/usr/local/lib/node_modules/spm/node_modules/cmd-util/lib/iduri.js:20
  var family = m[1] || '';
                ^
TypeError: Cannot read property '1' of null
    at Object.exports.resolve (/usr/local/lib/node_modules/spm/node_modules/cmd－util/lib/iduri.js:20:17)
    at /usr/local/lib/node_modules/spm/lib/install.js:71:20
    at q.process (/usr/local/lib/node_modules/spm/node_modules/async/lib/async.js:608:21)
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:901:3
```

**Comment by afc163** [comment]
好像不能带点，回头确认下。

**Comment by popomore** [comment]
id 规则是不能用点的，规则是 /a-zA-Z0-9-/

**Comment by willkan** [comment]
我觉得publish的时候应该检测一下组件名中是否含有 . 吧，我publish了一个这样名字的组件却无法unpublish........

**Comment by popomore** [comment]
恩，已经加了检测，谢谢提醒

**Comment by edokeh** [comment]
天啊，模块 ID 不能用 . 啊，好难过
规则这样定，是因为有啥冲突的场景吗？

**Comment by afc163** [comment]
鬼知道

**Comment by edokeh** [comment]
强烈要求修改此规则，包括支持下划线
